### ISSUE TITLE
All of the people have the default skin

### ISSUE THREAD

**Issue by LuckyMe3124** [Jamezo97/CloneCraft#31]
Every time i spawn a person, they either have the default "steve" skin or "alex" skin.

**Comment by GalaxyKitten42** [comment]
I'm having the same problem.

**Comment by TheLastSpectre** [comment]
This is due to an update to the Minecraft skin servers, causing the line of code that references the skin server to be defunct, forcing a default skin with every name.

**Comment by ZhandosC** [comment]
[@TheLastSpectre] Do You Think It'll Be Fixed Anytime Soon??

**Comment by TheLastSpectre** [comment]
Unfortunately not. I am, however, going to try and fix the code and reupload it, in the event that Jamezo never returns to the mod.

**Comment by Coolfin210** [comment]
I believe the mod has been fixed, however I don't know how to get the fixed version.
Edit: I put in the new version and I can obtain skins again! Thank you for fixing it.

**Comment by Jamezo97** [comment]
Heyo, yeah, try this. I've uploaded the latest version with the fixes.
Drop the the [CloneCraft-vB3.0.16.-.MC1.7.10.jar](https://github.com/Jamezo97/CloneCraft/releases/tag/v3.0.16-beta-mc-1.7.10) into the 'mods' folder in your .minecraft directory.
If it doesn't work or start, then please post a crash report, otherwise there is literally nothing I can do to help.
Good luck!
