### ISSUE TITLE
help the game isnt starting

### ISSUE THREAD

**Issue by helpme21** [Jamezo97/CloneCraft#32]
please fix it

**Comment by Jamezo97** [comment]
This only works for Minecraft 1.7.10. Drop the the [CloneCraft-vB3.0.16.-.MC1.7.10.jar](https://github.com/Jamezo97/CloneCraft/releases/tag/v3.0.16-beta-mc-1.7.10) into the 'mods' folder in your .minecraft directory.
If it doesn't work or start, then please post a crash report, otherwise there is literally nothing I can do to help.
Good luck!
